### ISSUE TITLE
Print choice

### ISSUE THREAD

**Issue by fredrikr** [daelsepara/secret-knights#2]
It would be better if the game printed the option I chose. In part as a confirmation that I didn't press the wrong key, but also to make a transcript make more sense.

Actually, it would probably be best if the game printed S when you save, D when you access the data bank etc, as well.

**Comment by daelsepara** [comment]
That does sounds sensible.. Should be a quick fix.

**Comment by daelsepara** [comment]
Added print output for story choices and other key-presses (A, D, F, H, ?, R, Q) in the latest release

Thanks for catching these.
