### ISSUE TITLE
Various typos

### ISSUE THREAD

**Issue by fredrikr** [daelsepara/secret-knights#3]
I think these are all typos.

It contains hints to hep you

a pair of grappling knights almost falls (should be "fall")

One of the dogs trots forward, baring it fangs. (should be "it's")

You're almost trampled by a wildly cheering crows. (should be "crowd")

Knights on horseback push slowly through the crows (should be "crowd")

You're waling through the crowded streets (should be "walking")

harness ship (should be "shop")

Back to the ship with you (should be "shop")

who might now about it (should be "know")

waling out the door (should be "walking")

He hold a red-hot piece (should be "holds")

"I've never seen you before, sweets. (a " is missing at the end)

what its like to be a knight (should be "it's")

come the the shrieks (an extra "the")

**Comment by daelsepara** [comment]
Fixed these typos and added a new .z5 release
